version: "2.0"
services:
  database:
    image: amsterdam/postgres11
    ports:
      - "5432:5432"
    environment:
      - DATABASE_NAME=
      - DATABASE_USER=
      - DATABASE_PASSWORD=
      - DATABASE_HOST=
      - DATABASE_PORT=
    volumes:
      - ~/.ssh/datapunt.key:/root/.ssh/datapunt.key
  
  api:
    build: ./api
    ports:
      - "8001:8001"
    links:
      - database
    environment:
      - APP_ID=
      - APP_KEY=
      - UWSGI_HTTP=0.0.0.0:8001
      - UWSGI_MASTER=1
      - UWSGI_STATIC_INDEX=index.html
      - UWSGI_STATIC_MAP=/mapitout-backend/static=/static
      - UWSGI_CALLABLE=application
      - UWSGI_VACUUM=1
      - UWSGI_STATIC_EXPIRES=/* 3600
      - UWSGI_OFFLOAD_THREADS=1
      - UWSGI_HARAKIRI=15
      - UWSGI_DIE_ON_TERM=1
      - UWSGI_MODULE=mapitout.wsgi:application
